import { useEffect } from "react";
import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";
import { sign } from "crypto";

export default function SignIn() {
  const { data: sessionData } = useSession();

  return (
    <>
      <Head>
        <title>Sign In</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col">
        <div className="flex w-full items-center justify-start">
          <button
            onClick={() => {
              signIn();
            }}
            className="m-3 rounded-lg bg-blue-600 px-2 py-1 font-sans text-white"
          >
            Sign In
          </button>
        </div>
      </main>
    </>
  );
}
